var data = {
	images: [
/* Tag Sorter */
		{
			src: [""],
			thumbnail: "",
			title: "Placeholder Entry",
			artist: "Placeholder Entry",
			artist_url: null,
			art_url: null,
			desc: "Do not delete this. You can use this to set the order the tags show up in the dropdown.",
			date_str: "Beginning of Time",
			tags: [""],
			hidden: true
		},
		{
			src: ["https://cdn.imgchest.com/files/3055d991d2ac.JPG"],
			thumbnail: "https://cdn.imgchest.com/files/22fbdf4933c7.png",
			title: "Edeleth",
			artist: "Rinku Bny",
			artist_url: "https://bsky.app/profile/rinkubny.bsky.social",
			art_url: null,
			desc: "The first image I had ever commissioned, although this was more of a Patreon request. Definitely interested in commissoning more Edeleth someday, though.",
			date_str: "May 2022",
			tags: ["other character", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/42cced1dff4d.PNG"],
			thumbnail: "https://cdn.imgchest.com/files/0337d49b7f48.png",
			title: "Sothstrid - Cuddling",
			artist: "Pomelomelon",
			artist_url: "https://bsky.app/profile/pomelomelon.bsky.social",
			art_url: null,
			desc: "The first image I had ever commissioned, the first commission of Sothe and Astrid, and the first commission with Pomelomelon. ...That's a lot of firsts.",
			date_str: "March 2023",
			tags: ["sothe", "astrid", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/b035f981ed1b.png"],
			thumbnail: "https://cdn.imgchest.com/files/3ca0ba62d66f.png",
			title: "Sothstrid - A Short Break",
			artist: "Adricarra",
			artist_url: "https://bsky.app/profile/adricarra.bsky.social",
			art_url: "https://x.com/adricarraART/status/1682749281717854209",
			desc: "The first Safe for Work illustration I commissioned, and the first from Adricarra.",
			date_str: "April 2023",
			tags: ["sothe", "astrid", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/9655368941e2.JPG"],
			thumbnail: "https://cdn.imgchest.com/files/5c06ffbe4689.png",
			title: "Shez's Endurance Training",
			artist: "NZZ",
			artist_url: "https://www.pixiv.net/en/users/1705529",
			art_url: "https://www.pixiv.net/en/artworks/109904854",
			desc: "First comm featuring Shez, Shamir, and Catherine.",
			date_str: "July 2023",
			tags: ["male_shez", "catherine", "shamir", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/eb0f36820154.png"],
			thumbnail: "https://cdn.imgchest.com/files/ce77e0c785df.png",
			title: "Arthur x Fee",
			artist: "Ebinku",
			artist_url: "https://www.pixiv.net/users/ebinkuu18",
			art_url: "https://www.pixiv.net/artworks/111756077",
			desc: "First comm from Ebinku.",
			date_str: "October 2023",
			tags: ["other character", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/3837712eee75.PNG"],
			thumbnail: "https://cdn.imgchest.com/files/7e37450acc72.png",
			title: "Shezmir",
			artist: "Pomelomelon",
			artist_url: "https://bsky.app/profile/pomelomelon.bsky.social",
			art_url: null,
			desc: null,
			date_str: "November 2023",
			tags: ["female_shez", "shamir", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/6321a011c059.JPG"],
			thumbnail: "https://cdn.imgchest.com/files/195053276f6e.png",
			title: "Atlas and Rearmed Sonya",
			artist: "Ebinku",
			artist_url: "https://x.com/ebinkuu",
			art_url: "https://x.com/ebinkuu/status/1748086690848084301",
			desc: "First comm of Atlas and Sonya. AKA the day I introduced people to my crackship for the first time.",
			date_str: "January 2024",
			tags: ["sonya", "atlas", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/317713e8e702.PNG"],
			thumbnail: "https://cdn.imgchest.com/files/f4b1a435dad0.png",
			title: "Forest Meeting",
			artist: "Tamafry",
			artist_url: "https://bsky.app/profile/tamafry.com",
			art_url: "https://x.com/tamafries/status/1756419768754614682",
			desc: "First of many comms from Tamafry. I also have a physical print version that I bought from them. This was also the piece that made me think I had something going here with these two, leading to me fully committing myself to them.",
			date_str: "February 2024",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/6feb58f2b275.PNG"],
			thumbnail: "https://cdn.imgchest.com/files/e002acf0a5bf.png",
			title: "Let's Have Some Fun",
			artist: "Ebinku",
			artist_url: "https://www.pixiv.net/stacc/ebinkuu18",
			art_url: "https://www.pixiv.net/en/artworks/118540970",
			desc: "A follow-up to my previous Sonya x Atlas piece.",
			date_str: "May 2024",
			tags: ["sonya", "atlas", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/bac1809c0552.JPG"],
			thumbnail: "https://cdn.imgchest.com/files/5c194aed2a20.png",
			title: "Serena Phraze",
			artist: "Etchimune",
			artist_url: "https://x.com/munedraws",
			art_url: "https://x.com/munedraws/status/1824148294769185138",
			desc: "A character from the Visual Novel/RPG Toushin Toshi Girl's Gift by Alicesoft, a remake of Toushin Toshi II for the PC-98. ...I just realized, she kinda looks like a teenage Catherine, doesn't she?",
			date_str: "August 2024",
			tags: ["other characters", "alicesoft", "visual novels", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/77eb65055be3.png"],
			thumbnail: "https://cdn.imgchest.com/files/b683f908af6e.png",
			title: "Shezlys",
			artist: "Sethkiel",
			artist_url: "https://x.com/SethsLilSecret",
			art_url: "https://x.com/SethsLilSecret/status/1836363150586695740",
			desc: "A shockingly underrated pairing I instantly fell in love with when I saw their supports.",
			date_str: "September 2024",
			tags: ["female_shez", "lysithea", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/ada31f963986.JPG"],
			thumbnail: "https://cdn.imgchest.com/files/373a267959a4.png",
			title: "Milli Yorks - Rance",
			artist: "Etchimune",
			artist_url: "https://x.com/munedraws",
			art_url: "https://x.com/munedraws/status/1841885143419777534",
			desc: "Milli from the RPG series Rance by Alicesoft, based on her outfit from Kichikuou Rance. If you're interested in playing it, I should warn you it does contain a LOT of NSFW.",
			date_str: "October 2024",
			tags: ["other characters", "alicesoft", "visual novels", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/c6a85273cb58.PNG"],
			thumbnail: "https://cdn.imgchest.com/files/352ec7b268cc.png",
			title: "Late Night Comfort",
			artist: "Adricarra (MissCherrylle)",
			artist_url: "https://bsky.app/profile/misscherrylle.bsky.social",
			art_url: "https://bsky.app/profile/misscherrylle.bsky.social/post/3lcl3d46pec25",
			desc: "I didn't realize how long I had gone without Sothstrid until I uploaded this piece lmao. Also my first VGen commission!",
			date_str: "December 3rd 2024",
			tags: ["astrid", "sothe", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/c2d14f129de0.JPG"],
			thumbnail: "https://cdn.imgchest.com/files/c4de55a7f9e7.png",
			title: "Sara Akizuki and Nagisa Shiono",
			artist: "Etchimune",
			artist_url: "https://x.com/munedraws",
			art_url: null,
			desc: "Two main characters from the Visual Novel Katei-Kyoushi no Onee-san by Atelier Kaguya. Yes, it's also a hentai, but one I found myself genuinely enjoying outside of the sex scenes.",
			date_str: "December 20th 2024",
			tags: ["other characters", "visual novels", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/5dd06b6831c6.PNG", "https://cdn.imgchest.com/files/18e2180a1a23.png", "https://cdn.imgchest.com/files/56afc3a0ed93.png", "https://cdn.imgchest.com/files/d2e5946fd4d4.png"],
			thumbnail: "https://cdn.imgchest.com/files/5b2db46a6951.png",
			title: "Toushin Toshi Girls' Gift Angels",
			artist: "Pomelomelon",
			artist_url: "https://bsky.app/profile/pomelomelon.bsky.social",
			art_url: null,
			desc: "More Girls Gift characters! From left to right, they are Pachikar, Hasaera Rabi, and Labelcase. They're only minor bosses in the game they appear in, but they have enough personality to stick in my mind despite this, especially Pachikar.",
			date_str: "January 13th 2025",
			tags: ["pachikar", "other characters", "alicesoft", "visual novels", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/50c8a0878347.JPG"],
			thumbnail: "https://cdn.imgchest.com/files/a75d37ce8994.png",
			title: "Shezlys - Forest Outing",
			artist: "Sethkiel",
			artist_url: "https://x.com/SethsLilSecret",
			art_url: "https://x.com/SethsLilSecret/status/1881098641139810523",
			desc: null,
			date_str: "January 17th, 2025",
			tags: ["female_shez", "lysithea", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/771d3d04d5cb.png"],
			thumbnail: "https://cdn.imgchest.com/files/d33d073784dc.png",
			title: "Sothstrid - Cute Couple",
			artist: "Symoca",
			artist_url: "https://x.com/symocosmos",
			art_url: "https://vgen.co/Symoca/portfolio/showcase/sothe-astrid/be5036d0-816a-4c6f-afcc-3490c0485fdf",
			desc: "First comm by Symoca. I love Astrid's expression here, she looks so cute!",
			date_str: "January 26th, 2025",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/267e803ada09.png"],
			thumbnail: "https://cdn.imgchest.com/files/ba4a62a6b751.png",
			title: "Sothstrid - Hot Spring Bonding",
			artist: "Tamafry",
			artist_url: "https://bsky.app/profile/tamafry.com",
			art_url: "https://bsky.app/profile/tamafry.com/post/3liqg2aqess27",
			desc: "The original idea behind this piece was for some kind of situation where Sothe suddenly hugged Astrid from behind, making her flustered. The idea was there, but I never knew how best to execute it.  Then I played Fire Emblem Heroes and was inspired by the Hot Spring event in that game's Heroes Journey event, and so this commission was born.",
			date_str: "February 2025",
			tags: ["astrid", "sothe", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/0f41fc81486b.JPG"],
			thumbnail: "https://cdn.imgchest.com/files/762251f07f84.png",
			title: "Summer Ursula",
			artist: "Etchimune",
			artist_url: "https://x.com/munedraws",
			art_url: "https://x.com/munedraws/status/1915445730849837344",
			desc: "Went through a period of rest for March due to financial stress at the time, but returned with a vengeance! ...Oh, and this piece, too.",
			date_str: "April 24th, 2025",
			tags: ["other characters", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/dadd01085e4a.JPG"],
			thumbnail: "https://cdn.imgchest.com/files/b9ca2124c189.png",
			title: "Dorothea's Romantic Fantasy",
			artist: "Sethkiel",
			artist_url: "https://x.com/SethsLilSecret",
			art_url: "https://x.com/SethsLilSecret/status/1921691226740261048",
			desc: "The idea for this piece was basically what I thought was Dorothea's perfect sexual fantasy. I decided on a romantic atmosphere with dim lights, rose petals... And a muscular Ingrid penetrating her with a strap-on.",
			date_str: "April 28th, 2025",
			tags: ["other characters", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/7cb999438739.PNG"],
			thumbnail: "https://cdn.imgchest.com/files/292b27c92f50.png",
			title: "Sothstrid - A Quiet Embrace",
			artist: "Adricarra",
			artist_url: "https://bsky.app/profile/adricarra.bsky.social",
			art_url: "https://bsky.app/profile/adricarra.bsky.social/post/3lpme53eafs2c",
			desc: "This piece... This fucking masterpiece... Is probably one of my all-time favorite SothStrid commissions. I really like Astrid's smile as she looks down at Sothe underneath her, and the way she has a hand on Sothe's cheek (and vice versa for Sothe). Also, I can confirm... Yes, they had sex beforehand.",
			date_str: "May 18th, 2025",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/297384fedba9.png"],
			thumbnail: "https://cdn.imgchest.com/files/75d481addebb.png",
			title: "Asako Machida - Circle Mate",
			artist: "Symoca",
			artist_url: "https://x.com/symocosmos",
			art_url: "https://vgen.co/Symoca/portfolio/showcase/asako-machida/3aa16119-37b6-47ca-97dd-8acdc5d55322",
			desc: "Character from the PC98 visual novel Circle Mate by Softhouse Bonbee Bonbon. The game was surprisingly good, and I wholeheartedly recommend it. Though there IS NSFW content in it.",
			date_str: "May 24th, 2025",
			tags: ["other characters", "visual novels", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/d3df805ce045.jpeg, https://cdn.imgchest.com/files/c7a7014c4739.jpeg, https://cdn.imgchest.com/files/681c0ea83605.jpeg, https://cdn.imgchest.com/files/aab458092059.jpeg, https://cdn.imgchest.com/files/c17a30bcaecb.jpeg, https://cdn.imgchest.com/files/36aca305bce9.jpeg, https://cdn.imgchest.com/files/68d84c1cd0ad.jpeg, https://cdn.imgchest.com/files/795dcab25325.jpeg"],
			thumbnail: "https://cdn.imgchest.com/files/6adb3c056eaf.png",
			title: "Lugh Mounting Melady",
			artist: "PinPin Ninja",
			artist_url: "https://www.pixiv.net/en/users/98799200",
			art_url: null,
			desc: "This was one of two pieces where I was being experimental with an Onee-Shota dynamic, expressing ideas that I felt could not be expressed anywhere else. I actually regret requesting these and don't like sharing them very much, but I'll still include them here for completion's sake.",
			date_str: "May 29th, 2025",
			tags: ["other characters", "fire emblem", "nsfw"],
			hidden: true
		},
		{
			src: ["https://cdn.imgchest.com/files/6645c7e1890b.PNG"],
			thumbnail: "https://cdn.imgchest.com/files/104b04464010.png",
			title: "Sothstrid - A Quick Snack",
			artist: "Pomelomelon",
			artist_url: "https://bsky.app/profile/pomelomelon.bsky.social",
			art_url: null,
			desc: "Man, this has to be one of my favorite NSFW Sothstrid comms. The way Astrid moans and looks down as Sothe eats her out... Oooof, that's good shit.",
			date_str: "June 13th 2025",
			tags: ["astrid", "sothe", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/c0c717852021.JPG"],
			thumbnail: "https://cdn.imgchest.com/files/e586d924d1c8.png",
			title: "Sothstrid - Ambush Hug",
			artist: "Sierra117Rennar",
			artist_url: "https://x.com/sierra117renner",
			art_url: "https://x.com/sierra117renner/status/1936636009032327223",
			desc: "Some of y'all may recognize this as my profile picture on BlueSky and Discord, lol.",
			date_str: "June 20th, 2025",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/b3f81e39fe1c.JPG"],
			thumbnail: "https://cdn.imgchest.com/files/08dbd2a85e21.png",
			title: "Summer Astrid",
			artist: "Etchimune",
			artist_url: "https://x.com/munedraws",
			art_url: "https://x.com/munedraws/status/1938276677831868674",
			desc: "The first commission that uses the summer design for Astrid I had conceived. The pendant she wears is the same one her grandmother gave her.",
			date_str: "June 26th, 2025",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/d945c588721c.png, https://cdn.imgchest.com/files/44798d71746d.png"],
			thumbnail: "https://cdn.imgchest.com/files/ebab50089d46.png",
			title: "Sothstrid - A Cozy Handjob",
			artist: "Symoca",
			artist_url: "https://x.com/symocosmos",
			art_url: null,
			desc: null,
			date_str: "June 27th, 2025",
			tags: ["astrid", "sothe", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/197d47578a31.PNG"],
			thumbnail: "https://cdn.imgchest.com/files/8b9ee1fd9706.png",
			title: "Sothstrid - Close Couple",
			artist: "Misokatsuhaumai",
			artist_url: "https://bsky.app/profile/misokatsuhaumai.bsky.social",
			art_url: "https://bsky.app/profile/misokatsuhaumai.bsky.social/post/3lszwzfzo5k2x",
			desc: "First comm from Mason aka Misokatsuhaumai. They would end up being one of my greatest supporters of the ship, and also instrumental in the creation of Estelle, Sothe and Astrid's fan-daughter.",
			date_str: "June 30 2025",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/04d044ca0069.JPG"],
			thumbnail: "https://cdn.imgchest.com/files/99c4fe49404d.png",
			title: "Sothstrid - Stargazing",
			artist: "Gzei",
			artist_url: "https://bsky.app/profile/gzeidraws.bsky.social",
			art_url: "https://bsky.app/profile/gzeidraws.bsky.social/post/3ltsxes7sl22g",
			desc: "This was an idea that had been sitting in my backlog for a long time, lol. Also, by pure coincidence, it was finished on my birthday. Definitely a good birthday gift though!",
			date_str: "July 11th 2025",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/395e5154d694.png"],
			thumbnail: "https://cdn.imgchest.com/files/d9f9c365dbed.png",
			title: "Sothstrid - Surprise Kiss",
			artist: "MajiBomber",
			artist_url: "https://bsky.app/profile/majibomber.bsky.social",
			art_url: null,
			desc: "This was actually based on an old Sothstrid piece from the stone age that I thought was really cute. I don't know who drew the original, as I found it randomly on Gelbooru and the uploader didn't credit them. That original can be found <a href=https://gelbooru.com/index.php?page=post&s=view&id=986437>here.</a>",
			date_str: "August 15th 2025",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/3663ff7d9416.png"],
			thumbnail: "https://cdn.imgchest.com/files/f87bcbf09b37.png",
			title: "Sothstrid - Summer Date",
			artist: "Ihsnet",
			artist_url: "https://x.com/Ihsnet",
			art_url: "https://x.com/Ihsnet/status/1958309494489801101?s=20",
			desc: "This is another piece that I really love. I really like how cute Astrid looks and how disgruntled Sothe is carrying her on his shoulders (even if he seems a little too angry for my liking.)",
			date_str: "August 19th, 2025",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/84283da6a041.png"],
			thumbnail: "https://cdn.imgchest.com/files/703edd754b17.png",
			title: "Astrid Book",
			artist: "Rotomdocs",
			artist_url: "https://bsky.app/profile/rotomdocs.bsky.social",
			art_url: null,
			desc: "The rare Rotomdocs commission after I was lucky enough to secure a slot with him. Man, I forgot how much I love this meme.",
			date_str: "August 22nd, 2025",
			tags: ["astrid", "fire emblem", "memes", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/4674727ba881.png", "https://cdn.imgchest.com/files/d19d76bf7544.png"],
			thumbnail: "https://cdn.imgchest.com/files/f56a2b857738.png",
			title: "Estelle",
			artist: "Misokatsuhaumai",
			artist_url: "https://bsky.app/profile/misokatsuhaumai.bsky.social",
			art_url: null,
			desc: "The very first image of Estelle, Sothe and Astrid's daughter, after existing as a small sketch inside my idea notebook. I remember Mason being VERY excited to draw her when I first sent the request to them, and I could tell throughout that they really enjoyed designing her. They even included an alternate color for Estelle's vest that until now I have never shared to anyone.",
			date_str: "September 13th, 2025",
			tags: ["estelle", "fire emblem", "original", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/c4f08ac21da8.jpg, https://cdn.imgchest.com/files/693e5f53cf55.jpg, "],
			thumbnail: "https://cdn.imgchest.com/files/d2779d8157be.png",
			title: "Sothstrid - Sothe Gets Rough",
			artist: "Sierra117Rennar",
			artist_url: "https://x.com/nsfw18_sierra",
			art_url: null,
			desc: "This was the first piece where I actually drew the reference myself instead of using a pre-existing image, and I really like how it turned out. Also Sierra sent me an alternate pose during the sketch process that I really liked, so I paid her extra to finish that extra sketch. Also the fact I got this around the same time I got my first Estelle comm... Hmmm...",
			date_str: "September 14th, 2025",
			tags: ["astrid", "sothe", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/60c9a0a4ecaa.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/3c8eaf87965c.png",
			title: "Catherine and Shez Making Love",
			artist: "Sethkiel",
			artist_url: "https://x.com/SethsLilSecret",
			art_url: "https://x.com/SethsLilSecret/status/1982988872180215833",
			desc: "A sort of rarepair from Three Hopes that I found myself really liking, even though I haven't commissioned them often. I really love the passion between them in this piece.",
			date_str: "September 14th, 2025",
			tags: ["male_shez", "catherine", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/8b8145192600.png"],
			thumbnail: "https://cdn.imgchest.com/files/6332108235d5.png",
			title: "Sothstrid - Supply Run",
			artist: "LazzleDazzle",
			artist_url: "https://bsky.app/profile/lazzledazzle.bsky.social",
			art_url: null,
			desc: "A funny little 4koma from Lazzle, based on another idea that had sat in my backlog for a long time. Featuring Marcia from the Fire Emblem series.",
			date_str: "October 2nd, 2025",
			tags: ["astrid", "sothe", "marcia", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/3161070c9dd3.png"],
			thumbnail: "https://cdn.imgchest.com/files/a001b764c2af.png",
			title: "Sothstrid - Walking by The Sea",
			artist: "Tamafry",
			artist_url: "https://bsky.app/profile/tamafry.com",
			art_url: "https://bsky.app/profile/tamafry.com/post/3m2uw7sszms2f",
			desc: "This actually came out a little later than I had wanted, but the art itself did NOT disappoint me. Once again, Tama really outdid themselves here.",
			date_str: "October 8th, 2025",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/a7c62b258108.png, https://cdn.imgchest.com/files/e8d5503bf767.png, https://cdn.imgchest.com/files/ab033ab11dc4.png, https://cdn.imgchest.com/files/df7757741bba.png, https://cdn.imgchest.com/files/b45b2f8b69dd.png, https://cdn.imgchest.com/files/0a7561bf550b.png, https://cdn.imgchest.com/files/552247597ebb.png, https://cdn.imgchest.com/files/c75af2455487.png"],
			thumbnail: "https://cdn.imgchest.com/files/72121bca16b8.png",
			title: "Elen and Lugh Onee-shota Sex",
			artist: "Oyatsu_0",
			artist_url: "https://www.pixiv.net/en/users/71112175",
			art_url: "https://www.pixiv.net/en/artworks/137441593",
			desc: "Another experimental shotacon piece that, unfortunately, I regret requesting. Again, I don't like sharing this one because of that, but I'll still include it for completion's sake.",
			date_str: "October 22nd, 2025",
			tags: ["other characters", "fire emblem", "nsfw"],
			hidden: true
		},
		{
			src: ["https://cdn.imgchest.com/files/944f38d79d78.png"],
			thumbnail: "https://cdn.imgchest.com/files/c0efdc5c03af.png",
			title: "Sothstrid - Artistic Nude",
			artist: "Rani-Ki",
			artist_url: "https://bsky.app/profile/rani-ki.bsky.social",
			art_url: null,
			desc: "What can I say about this piece? It's absolutely beautiful and I love it.",
			date_str: "October 27th, 2025",
			tags: ["astrid", "sothe", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/290beb2db86c.png"],
			thumbnail: "https://cdn.imgchest.com/files/bb3fd996f922.png",
			title: "Sothstrid - Happy Halloween!",
			artist: "Symoca",
			artist_url: "https://x.com/symocosmos",
			art_url: "https://vgen.co/Symoca/portfolio/showcase/halloween-astrid-and-sothe-/e42b59f4-2499-4a93-85c4-d89eb37c55c5",
			desc: "As the title implies, this was intended to be made on Halloween. However, I KINDA forgot to actually request it until a few days before Halloween. As a result I told Symoca that I wanted this done quickly, though still within a reasonable timeframe, and she accepted. I am forever grateful for the fact she accepted the request on such short notice.",
			date_str: "November 2nd, 2025",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/83074ad01815.png"],
			thumbnail: "https://cdn.imgchest.com/files/00b1f68f31d6.png",
			title: "Sothstrid - Special Feeling",
			artist: "LazzleDazzle",
			artist_url: "https://bsky.app/profile/lazzledazzle.bsky.social",
			art_url: null,
			desc: "A recreation of the \"Special Feeling\" meme with Sothe and Astrid.",
			date_str: "November 16th, 2025",
			tags: ["astrid", "sothe", "fire emblem", "memes", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/26f78f31e2bc.png"],
			thumbnail: "https://cdn.imgchest.com/files/31b3a97fb098.png",
			title: "Sothstrid - Pixel Art",
			artist: "Evomanaphy",
			artist_url: "https://bsky.app/profile/evomanaphy.bsky.social",
			art_url: null,
			desc: "The first time I commissioned Evomanaphy after wanting to commission them for a long time. I really love how cute this ended up being.",
			date_str: "November 25th, 2025",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/b18b8941b911.png"],
			thumbnail: "https://cdn.imgchest.com/files/8ca31d7a2650.png",
			title: "Astrid (Zedora)",
			artist: "Zedora",
			artist_url: "https://bsky.app/profile/zedoraart.bsky.social",
			art_url: "https://bsky.app/profile/zedoraart.bsky.social/post/3m6n66z2g6c2x",
			desc: "A rare commission where I requested Astrid on her own without Sothe.",
			date_str: "November 26th, 2025",
			tags: ["astrid", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/34f0bf65d828.png"],
			thumbnail: "https://cdn.imgchest.com/files/890aaf4344ed.png",
			title: "Are You a Virgin?",
			artist: "Pomelomelon",
			artist_url: "https://bsky.app/profile/pomelomelon.bsky.social",
			art_url: null,
			desc: "A recreation of the \"Are You a Virgin?\" meme from Tokyo Ghoul with Sonya and Atlas. This was originally going to be yet another Sothe x Astrid piece (because I'm so predictable), but I decided to go with Sonya x Atlas instead because 1) It's been a while since I commissioned something with them, and 2) I thought it was more in-character for Sonya to ask the question to someone.",
			date_str: "December 2nd, 2025",
			tags: ["sonya", "atlas", "fire emblem", "memes", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/dd4798ae759c.png", "https://cdn.imgchest.com/files/864c702185a4.png", "https://cdn.imgchest.com/files/8bcecd20179d.png"],
			thumbnail: "https://cdn.imgchest.com/files/246a1a7eec82.png",
			title: "Astrid - Filter-Heavy Doodle",
			artist: "Misokatsuhaumai",
			artist_url: "https://bsky.app/profile/misokatsuhaumai.bsky.social",
			art_url: "https://bsky.app/profile/misokatsuhaumai.bsky.social/post/3m77rq5vs7s2n",
			desc: "One of the Mason's \"Filter-Heavy Doodles\" that they would post on X to keep their X account alive, before ultimately deleting it entirely. Since they deleted it, I was given permission by Mason to upload the non-filtered version here.",
			date_str: "December 5th, 2025",
			tags: ["astrid", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/249ce3a74d53.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/d3301fc1a4cd.png",
			title: "Sothe, Astrid, and Baby Estelle",
			artist: "Gzei",
			artist_url: "https://bsky.app/profile/gzeidraws.bsky.social",
			art_url: "https://bsky.app/profile/gzeidraws.bsky.social/post/3m7ojek4x3224",
			desc: "A fun idea I had when I started thinking about what Sothe and Astrid would be like as parents, especially when Estelle was younger. Gzei absolutely nailed the idea as always. I especially love the little pouting expression Estelle has.",
			date_str: "December 10th, 2025",
			tags: ["astrid", "sothe", "estelle", "fire emblem", "original", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/c87b81ef66a1.png"],
			thumbnail: "https://cdn.imgchest.com/files/6daaec0b4a1b.png",
			title: "Sothstrid Swimsuit Request",
			artist: "Rotomdocs",
			artist_url: "https://x.com/RotomDocs",
			art_url: "https://x.com/rotomdocs/status/2000752566003753314",
			desc: "Another rare Rotomdocs comm that I was somehow lucky enough to get. Looking at it again, I never realized until now how much I needed Sothe with abs...",
			date_str: "December 11th 2025",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/f5ad572f0f54.png", "https://cdn.imgchest.com/files/b49ecca6c93e.png", "https://cdn.imgchest.com/files/ef2b32fe85ab.png", "https://cdn.imgchest.com/files/2331d6884f17.png", "https://cdn.imgchest.com/files/8a593f27d8ce.png", "https://cdn.imgchest.com/files/0d05c41ecbc3.png"],
			thumbnail: "https://cdn.imgchest.com/files/210908a76618.png",
			title: "Estelle Relaxing",
			artist: "Aduti Momoyama",
			artist_url: "https://www.pixiv.net/en/users/2210855",
			art_url: "https://skeb.jp/@aduti_momoyama/works/31",
			desc: "This was one of my first commissions through Skeb after being unable to use it for years due to Credit Card Issues. I honestly really like how it turned out, though in my opinion the mouth looks a little off. What I didn't expect was that the artist ALSO sent me several rough sketches showing alternate poses for her, some of which actually looked pretty interesting (as shown here.) I really like the second and third one out of those sketches, even if number 3 is a little out of character for Estelle. The first sketch looks like she's about to rape me, though. Eugh.",
			date_str: "December 22nd 2025",
			tags: ["estelle", "fire emblem", "original", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/7c3c8623153e.png"],
			thumbnail: "https://cdn.imgchest.com/files/f0c96b28cc5f.png",
			title: "Modern Sothstrid",
			artist: "Wwitchii",
			artist_url: "https://bsky.app/profile/wwitchii.bsky.social",
			art_url: "https://bsky.app/profile/wwitchii.bsky.social/post/3mb34odyfts2b",
			desc: "Sothe and Astrid in a modern setting. Astrid looking flustered around Sothe is honestly cute and I love it.",
			date_str: "December 28th 2025",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/65f1e0029305.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/56510ed7545f.jpg",
			title: "Estelle Throwing a Dagger",
			artist: "Sierra117Rennar",
			artist_url: "https://x.com/sierra117renner",
			art_url: "https://vgen.co/s117renner/portfolio/showcase/loneshadowstar-s-oc/a3bd146b-93c6-4cfd-9ca6-42db4364754e",
			desc: "An action shot piece with Estelle. Dunno what you did to make her throw a dagger at you, though.",
			date_str: "December 29th 2025",
			tags: ["estelle", "fire emblem", "original", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/01cc10d2a520.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/88b304803539.png",
			title: "Lex's Counterattack",
			artist: "Ebinku",
			artist_url: "https://x.com/ebinkuu18",
			art_url: "https://x.com/ebinkuu18/status/2009045574906265742",
			desc: "First Comm of 2026, featuring the glorious return of Ebinku! Lex and Ayra were always one of my favorite Genealogy pairings, and I had wanted to commission them for a long time. As usual, Ebinku really cooked here.",
			date_str: "January 7th 2026",
			tags: ["other characters", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/d2bbae062e6e.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/d0799f8118f7.jpg",
			title: "Astrid, Exposed",
			artist: "SonicHeroXD",
			artist_url: "https://x.com/SonicHeroXD",
			art_url: "https://x.com/sonicheroxd/status/2015855508486307958",
			desc: null,
			date_str: "January 26th 2026",
			tags: ["astrid", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/8d4876315a5e.png", "https://cdn.imgchest.com/files/34bae1931609.png", "https://cdn.imgchest.com/files/ed1c5d38be98.png", "https://cdn.imgchest.com/files/6f270f569d9f.png", "https://cdn.imgchest.com/files/fe99162feefc.png", "https://cdn.imgchest.com/files/069e0bcb4876.png", "https://cdn.imgchest.com/files/6576fda70b8f.png"],
			thumbnail: "https://cdn.imgchest.com/files/df5e3a0618c5.png",
			title: "Vote Astrid for CYL! (and Sothe too)",
			artist: "Majibomber",
			artist_url: "https://bsky.app/profile/majibomber.bsky.social",
			art_url: null,
			desc: "Some last minute Choose your Legends 2026 propaganda for Astrid, completed on the last day of the event. I actually almost used Makalov in Estelle's place, but changed my mind because fuck Makalov. Maji had also included separated versions for each character, as well as blank versions, so I added those.",
			date_str: "January 28th 2026",
			tags: ["astrid", "sothe", "marcia", "estelle", "other characters", "fire emblem", "sfw"],
			hidden: false
		},
			{
			src: ["https://cdn.imgchest.com/files/a30823a69a97.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/06872f976751.png",
			title: "Sothstrid Christmas",
			artist: "Sierra117Rennar",
			artist_url: "https://x.com/Sierra117renner",
			art_url: "https://x.com/sierra117renner/status/2017004220294320232",
			desc: "Another planned holiday piece that unfortunately did not make it on time. Though part of this was because Sierra had a large workload at the time I requested it, so I won't hold it against her.",
			date_str: "January 29th 2026",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/5a97ebfa1808.png", "https://cdn.imgchest.com/files/465a281786aa.png"],
			thumbnail: "https://cdn.imgchest.com/files/0a7171c2d94c.png",
			title: "Kyouko and Akira Nanami",
			artist: "Symoca",
			artist_url: "https://x.com/symocosmos",
			art_url: "https://vgen.co/Symoca/portfolio/showcase/akira-and-kyouka-doodle/c96c92ec-6585-4b1d-b20c-4cb2ecba9ae6",
			desc: "Two characters from the visual novel \"Boku to Gonee to Umi no Year!\", or \"Me, 5 sisters, and the Year of The Sea!\" in English. The game itself is kinda mid story-wise, but it makes up for that with great 2000s-era artwork by Shunsaku Tomose, a name you may or may not be familiar with.",
			date_str: "February 11th 2026",
			tags: ["other characters", "visual novels", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/d4c3fea809e3.png"],
			thumbnail: "https://cdn.imgchest.com/files/eafc62860605.png",
			title: "Sothstrid Valentine's",
			artist: "LazzleDazzle",
			artist_url: "https://bsky.app/profile/lazzledazzle.bsky.social",
			art_url: null,
			desc: "Hey, look! A holiday-specific comm I remembered to request WITHOUT waiting until the last second! Jokes aside, though, I love the way this turned out. Astrid's > < expression needs no words on how cute it is, and I'm also proud of the casual outfits I came up with for them (even though all I did was have Lazzle remove Sothe's vest and weapons and Astrid's armor and cape lmao.)",
			date_str: "February 14th 2026",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/eba52d5dd686.png"],
			thumbnail: "https://cdn.imgchest.com/files/444d6e4e75f6.png",
			title: "Sothe and Astrid Sleeping Together",
			artist: "RedKite333",
			artist_url: "https://x.com/RedKite333",
			art_url: "https://x.com/RedKite333/status/2025016046013612335",
			desc: "A fine addition to this artist's \"Couples Lying Together\" collection!",
			date_str: "February 20th 2026",
			tags: ["astrid", "sothe", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/29aa8c0f2200.png"],
			thumbnail: "https://cdn.imgchest.com/files/e7f195482c47.png",
			title: "Male Kris, Athena, and Malice Threesome",
			artist: "Pomelomelon",
			artist_url: "https://bsky.app/profile/pomelomelon.bsky.social",
			art_url: null,
			desc: "I started shipping Athena and Malice with Kris after seeing their supports in New Mystery. Since they're both Myrmidons, I thought \"Why not have a threesome between them?\"",
			date_str: "March 5th 2026",
			tags: ["other characters", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/10f9ea131d22.png", "https://cdn.imgchest.com/files/07713bbeeb5e.png"],
			thumbnail: "https://cdn.imgchest.com/files/7dcb08784067.png",
			title: "Pachikar Handjob",
			artist: "DHA",
			artist_url: "https://www.pixiv.net/en/users/41750",
			art_url: "https://skeb.jp/@dha_l/works/275",
			desc: "Pachikar returns with a vengeance! Also managed to snag a never-before-seen ejaculation alt that was hidden in the PSD file.",
			date_str: "March 7th 2026",
			tags: ["pachikar", "alicesoft", "visual novels", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/3450b23c5d38.png"],
			thumbnail: "https://cdn.imgchest.com/files/d7d8041be777.png",
			title: "Sothstrid - A Priceless Gift",
			artist: "Tamafry",
			artist_url: "https://bsky.app/profile/tamafry.com",
			art_url: "https://bsky.app/profile/tamafry.com/post/3mgy2boccal2b",
			desc: "This is an idea I came up with during a conversation between me and Tama during my last commission with them. I knew from Astrid's supports with Makalov that she didn't mind giving away the pendant her Grandmother gave her, so I decided to request a more wholesome version of that with Sothe. This takes place after the endgame of Radiant Dawn, so Sothe and Astrid are in their Third Tier Class outfits.",
			date_str: "March 13th 2026",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/e58be89ff804.jpg", "https://cdn.imgchest.com/files/e252ecadcebf.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/af8b2c2b957e.png",
			title: "Sothstrid - Keeping Astrid Close",
			artist: "Pudel",
			artist_url: "https://ko-fi.com/P5P125VWA",
			art_url: null,
			desc: "An artist I commissioned on ko-fi after being recommended to by another commissioner. I'm glad I listened to them, because this is some good shit here.",
			date_str: "March 26th 2026",
			tags: ["astrid", "sothe", "fire emblem", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/13e4a452c0aa.jpg", "https://cdn.imgchest.com/files/ae6dd2db2996.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/5ec627cf790f.png",
			title: "Thjazi Pegging Kiran",
			artist: "Lewdpala",
			artist_url: "https://bsky.app/profile/lewdpala.bsky.social",
			art_url: null,
			desc: "Muscular women...",
			date_str: "March 27th 2026",
			tags: ["other characters", "fire emblem", "nsfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/7995d738f126.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/82f3860ed082.png",
			title: "Sothstrid Passion",
			artist: "Ihsnet",
			artist_url: "https://x.com/LambdaIhs",
			art_url: null,
			desc: "Man, the passion in this image is palpable.",
			date_str: "March 30th 2026",
			tags: ["astrid", "sothe", "fire emblem", "nsfw"],
			hidden: false
		},
/* Template */
		{
			src: [""],
			thumbnail: "",
			title: "",
			artist: "",
			artist_url: "",
			art_url: "",
			desc: "",
			date_str: "",
			tags: [""],
			hidden: true
		}
	]
};
